# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17daa3aa70ee9348dce26d743b7f5f9c05c971597f2a26342098b2532bb9fa12ea2eec808565d9c3274f4c2c09c72cbc06f3f293a27a7639133c00b9f1a1d387

test:
  secret_key_base: 4ce64557fbc127e0bdd1f7ebf5241b6cfa605649db3cb1fac0a0adf38d5ab76b0f119c2a29d042f5f9f037f61ea7f4f2b99898590ae6a71cdf515b1ca1862880

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
